name: 'Copy to Another Repository'
description: 'Copy selected file to another repository and create Pull Request (PR).'
author: 'Sator Imaging'
branding:
  icon: copy
  color: purple


inputs:
  target-filepath:
    required: true
    description: 'File path to copy.'
  output-repo:
    required: true
    description: 'Owner/AnotherRepository'
  output-branch:
    required: true
    description: 'Branch name on output repository to create pull request.'
  commit-message-prefix:
    default: '[actions] '
  output-directory:
    default: "${{ github.event.repository.name }}"
  pr-branch-prefix:
    default: "actions/${{ github.event.repository.name }}"
  pr-title:
    default: "GitHub Actions: ${{ github.event.repository.name }}"
  pr-message:
    default: "Workflow: ${{ github.workflow }} on ${{ github.server_url }}/${{ github.repository }}"
  git-name:
    default: "${{ github.actor }}"
  git-email:
    description: 'Use your "@users.noreply.github.com" address if you want your icon shown in commit messages.'
    default: 'devnull@inter.net'
  git-token:
    required: true
    description: 'Personal Access Token used to commit/create PR on output repository.'


runs:
  using: 'composite'
  steps:
    - run: echo '::echo::on'
      shell: bash

    - run: echo "PR_BRANCH=${{ inputs.pr-branch-prefix }}---$(date +'%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV
      shell: bash
    - run: echo "ACTION_REPO=$( echo $GITHUB_ACTION | sed 's/_/\//g' )" >> $GITHUB_ENV
      shell: bash
    - run: echo "ACTION_REPO=${${{ env.ACTION_REPO }}/\//}" >> $GITHUB_ENV
      shell: bash
    - run: echo "PR_MESSAGE=${{ inputs.pr-message }}\\n${{ env.ACTION_REPO }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "TMP_SRCDIR=./source" >> $GITHUB_ENV
      shell: bash
    - run: echo "TMP_DSTDIR=./dest" >> $GITHUB_ENV
      shell: bash

    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        path: "${{ env.TMP_SRCDIR }}"

    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        path: "${{ env.TMP_DSTDIR }}"
        repository: "${{ inputs.output-repo }}"

    # composite test
    - name: composite test
      run: ls .
      shell: bash
      if: ${{ github.event_name == 'push' }}
    - run: ls .
      shell: bash
      working-directory: "${{ env.TMP_DSTDIR }}"
    - run: ls .
      shell: bash
      working-directory: "${{ env.TMP_DSTDIR }}"

    - run: echo "${{ github.event.commits[0] }}"
      shell: bash
    - run: echo "${{ github.event.commits[0].url }}"
      shell: bash
    - run: echo "${{ github.event.commits[0].modified }}"
      shell: bash
    - run: echo "${{ github.event.commits[0].modified[0] }}"
      shell: bash
    - run: echo "${{ github.event.commits[0].modified[0].path }}"
      shell: bash

    - run: git config --global user.name "${{ inputs.git-name }}"
      shell: bash
    - run: git config --global user.email "${{ inputs.git-email }}"
      shell: bash
    - run: git config --global url."https://${{ inputs.git-token }}@github.com/".insteadOf "https://github.com/"
      shell: bash

    - run: cd "${{ env.TMP_DSTDIR }}"
      shell: bash
      # we cannot change current directory
    - run: ls .
      shell: bash

    - run: git -C "${{ env.TMP_DSTDIR }}" checkout -b "${{ env.PR_BRANCH }}"
      shell: bash

    - run: mkdir -p "${{ env.TMP_DSTDIR }}/${{ inputs.output-directory }}"
      shell: bash
    - run: mv -f "${{ env.TMP_SRCDIR }}/${{ inputs.target-filepath }}" "${{ env.TMP_DSTDIR }}/${{ inputs.output-directory }}"
      shell: bash

    - run: git -C "${{ env.TMP_DSTDIR }}" add "${{ inputs.output-directory }}/."
      shell: bash
    - run: git -C "${{ env.TMP_DSTDIR }}" commit -am "${{ inputs.commit-message-prefix }}${{ github.event.repository.name }}"
      shell: bash
    - run: git -C "${{ env.TMP_DSTDIR }}" push origin HEAD
      shell: bash

    # adding this will cause syntax error... -H "Accept: application/vnd.github.v3+json"
    - run: curl -X POST "https://${{ inputs.git-token }}@api.github.com/repos/${{ inputs.output-repo }}/pulls" -d "{ \"title\":\"${{ inputs.pr-title }}\", \"body\":\"${{ env.PR_MESSAGE }}\", \"head\":\"${{ env.PR_BRANCH }}\", \"base\":\"${{ inputs.output-branch }}\" }"
      shell: bash
