name: 'Deploy to Another Repository'
description: 'Deploy and Create Pull Request'
author: 'Sator Imaging'
branding:
  icon: copy
  color: purple


inputs:
  target-filepath:
    required: true
    description: 'README.md'
  output-repo:
    required: true
    description: 'SatorImaging/OpenManual'
  output-branch:
    required: true
    description: 'master'
  output-directory:
    default: "${{ github.event.repository.name }}"
  pr-branch-prefix:
    default: "${{ github.event.repository.name }}"
  pr-title:
    default: "GitHub Actions: ${{ github.workflow }}"
  pr-message:
    default: " "
  git-name:
    default: "${{ github.actor }}"
  git-email:
    default: "devnull@inter.net"
  git-token:
    required: true
    description: "Personal Access Token for Output Repository"


runs:
  using: 'composite'
  steps:
  - run: echo "PR_BRANCH=${{ inputs.pr-branch-prefix }}---$(date +'%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV
    shell: bash
  - run: echo "TMP_SRCDIR=./source" >> $GITHUB_ENV
    shell: bash
  - run: echo "TMP_DSTDIR=./dest" >> $GITHUB_ENV
    shell: bash

    uses: actions/checkout@v3
    with:
      persist-credentials: false
      path: "./source"

    uses: actions/checkout@v3
    with:
      persist-credentials: false
      path: "./dest"
      repository: "${{ inputs.output-repo }}"

  - run: ls .
    shell: bash
  - run: git config --global user.name "${{ inputs.git-name }}"
    shell: bash
  - run: git config --global user.email "${{ inputs.git-email }}"
    shell: bash
  - run: git config --global url."https://${{ inputs.git-token }}@github.com/".insteadOf "https://github.com/"
    shell: bash

  - run: cd "$TMP_DSTDIR"
    shell: bash
  - run: git checkout -b "${PR_BRANCH}"
    shell: bash
  - run: echo "$PR_BRANCH"
    shell: bash

  - run: mkdir "${{ inputs.output-directory }}"
    shell: bash
  - run: mv -f "../${TMP_SRCDIR}/${{ inputs.target-filepath }}" "${{ inputs.output-directory }}"
    shell: bash

  - run: git add "."
    shell: bash
  - run: git commit -am "${{ github.repository }} at `date`"
    shell: bash
  - run: git push origin HEAD
    shell: bash
