name: 'Deploy to Another Repository'
description: 'Deploy and Create Pull Request'
author: 'Sator Imaging'
branding:
  icon: copy
  color: purple


inputs:
  target-filepath:
    required: true
    description: 'README.md'
  output-repo:
    required: true
    description: 'SatorImaging/OpenManual'
  output-branch:
    required: true
    description: 'master'
  output-directory:
    default: "${{ github.event.repository.name }}"
  pr-branch-prefix:
    default: "${{ github.event.repository.name }}"
  pr-title:
    default: "GitHub Actions: ${{ github.workflow }}"
  pr-message:
    default: ""
  git-name:
    default: "${{ github.actor }}"
  git-email:
    default: "devnull@inter.net"
  git-token:
    required: true
    default: ""


env:
  TMP_SRCDIR: './source'
  TMP_DSTDIR: './dest'

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
    with:
      persist-credentials: false
      path: "${{ env.TMP_SRCDIR }}"

  - uses: actions/checkout@v3
    with:
      persist-credentials: false
      repository: "${{ inputs.output-repo }}"
      path: "${{ env.TMP_DSTDIR }}"

  - name: Commit & PR
    run: git config --global user.name "${{ inputs.git-name }}"
      shell: bach
    run: git config --global user.email "${{ inputs.git-email }}"
      shell: bach
    run: git config --global url."https://${{ inputs.git-token }}@github.com/".insteadOf "https://github.com/"
      shell: bach

    run: cd "${TMP_DSTDIR}"
      shell: bach
    run: git checkout -b "${{ inputs.pr-branch-prefix }}---$(date +'%Y-%m-%d--%H-%M-%S')"  # branch name must be same with curl JSON.head.
      shell: bach

    run: mkdir "${{ inputs.output-directory }}"
      shell: bach
    run: mv -f "../${TMP_SRCDIR}/${{ inputs.target-filepath }}" "${{ inputs.output-directory }}"
      shell: bach

    run: git add "."
      shell: bach
    run: git commit -am "${{ github.repository }} at `date`"
      shell: bach
    run: git push origin HEAD
      shell: bach

    run: curl -X POST \
        -H 'Accept: application/vnd.github.v3+json' \
        "https://${{ inputs.git-token }}@api.github.com/repos/${{ inputs.output-repo }}/pulls" \
        -d "{ \"title\":\"${{ inputs.pr-title }}\", \"body\":\"${{ inputs.pr-message }}\", \"head\":\"${{ inputs.pr-branch-prefix }}---$(date +'%Y-%m-%d--%H-%M-%S')\", \"base\":\"${{ inputs.output-branch }}\" }"
      shell: bash
