name: 'Deploy to Another Repository'
description: 'Deploy and Create Pull Request'
author: 'Sator Imaging'
branding:
  icon: copy
  color: purple


inputs:
  target-filepath:
    required: true
    description: 'README.md'
  output-repo:
    required: true
    description: 'SatorImaging/OpenManual'
  output-branch:
    required: true
    description: 'master'
  output-directory:
    default: "${{ github.event.repository.name }}"
  pr-branch-prefix:
    default: "${{ github.event.repository.name }}"
  pr-title:
    default: "GitHub Actions: ${{ github.workflow }}"
  pr-message:
    default: " "
  git-name:
    default: "${{ github.actor }}"
  git-email:
    default: "devnull@inter.net"
  git-token:
    required: true
    description: "Personal Access Token for Output Repository"


runs:
  using: 'composite'
  steps:
  - run: echo "PR_BRANCH=${{ inputs.pr-branch-prefix }}---$(date +'%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV
    shell: bash
  - run: echo "TMP_SRCDIR=./source" >> $GITHUB_ENV
    shell: bash
  - run: echo "TMP_DSTDIR=./dest" >> $GITHUB_ENV
    shell: bash

  - uses: actions/checkout@v3
    with:
      persist-credentials: false
      path: "${{ env.TMP_SRCDIR }}"

  - uses: actions/checkout@v3
    with:
      persist-credentials: false
      path: "${{ env.TMP_DSTDIR }}"
      repository: "${{ inputs.output-repo }}"

  - run: ls .
    shell: bash

  - run: git config --global user.name "${{ inputs.git-name }}"
    shell: bash
  - run: git config --global user.email "${{ inputs.git-email }}"
    shell: bash
  - run: git config --global url."https://${{ inputs.git-token }}@github.com/".insteadOf "https://github.com/"
    shell: bash

  - run: cd "${{ env.TMP_DSTDIR }}"
    shell: bash
    # we cannot change current directory
  - run: ls .
    shell: bash

  - run: git -C "${{ env.TMP_DSTDIR }}" checkout -b "${{ env.PR_BRANCH }}"
    shell: bash


  - run: mkdir "${{ env.TMP_DSTDIR }}/${{ inputs.output-directory }}"
    shell: bash
  - run: mv -f "${{ env.TMP_SRCDIR }}/${{ inputs.target-filepath }}" "${{ env.TMP_DSTDIR }}/${{ inputs.output-directory }}"
    shell: bash

  - run: git -C "${{ env.TMP_DSTDIR }}" add "${{ inputs.output-directory }}/."
    shell: bash
  - run: git -C "${{ env.TMP_DSTDIR }}" commit -am "${{ github.repository }} at `date`"
    shell: bash
  - run: git -C "${{ env.TMP_DSTDIR }}" push origin HEAD
    shell: bash
