name: 'Deploy to Another Repository'
description: 'Deploy and Create Pull Request'
author: 'Sator Imaging'
branding:
  icon: copy
  color: purple


inputs:
  target-filepath:
    description: 'README.md'
  output-repo:
    description: 'SatorImaging/OpenManual'
  output-branch:
    description: 'master'
  output-directory:
    required: false
    default: "${{ github.event.repository.name }}"
  pr-branch-prefix:
    required: false
    default: "${{ github.event.repository.name }}"
  pr-title:
    required: false
    default: "GitHub Actions: ${{ github.workflow }}"
  pr-message:
    required: false
    default: ""
  git-name:
    required: false
    default: "${{ github.actor }}"
  git-email:
    required: false
    default: "devnull@inter.net"
  git-token:
    default: ""


env:
  TMP_SRCDIR: './source'
  TMP_DSTDIR: './dest'


runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
    with:
      persist-credentials: false
      path: "${{ env.TMP_SRCDIR }}"

  - uses: actions/checkout@v3
    with:
      persist-credentials: false
      repository: "${{ inputs.output-repo }}"
      path: "${{ env.TMP_DSTDIR }}"

  - name: Update Env
    run: echo "PR_BRANCH=${{ inputs.pr-branch-prefix }}---$(date +'%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV

  - name: Commit & PR
    run: |
      git config --global user.name "${{ inputs.git-name }}"
      git config --global user.email "${{ inputs.git-email }}"
      git config --global url."https://${{ inputs.git-token }}@github.com/".insteadOf "https://github.com/"

      cd "${TMP_DSTDIR}"
      git checkout -b "${PR_BRANCH}"

      mkdir "${{ inputs.output-directory }}"
      mv -f "../${TMP_SRCDIR}/${{ inputs.target-filepath }}" "${{ inputs.output-directory }}"

      git add "."
      git commit -am "${{ github.repository }} at `date`"
      git push origin HEAD

      curl -X POST \
        -H 'Accept: application/vnd.github.v3+json' \
        "https://${{ inputs.git-token }}@api.github.com/repos/${{ inputs.output-repo }}/pulls" \
        -d "{ \"title\":\"${{ inputs.pr-title }}\", \"body\":\"${{ inputs.pr-message }}\", \"head\":\"${PR_BRANCH}\", \"base\":\"${{ inputs.output-branch }}\" }"
