name: AutoTagging   # auto-tagging to latest commit (not release commit)

on:
  release:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Tagging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete "v1" --yes
          gh release create "v1" --notes "Tagged by GitHub Actions"
