name: Deploy2OM

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: sator-imaging/Copy-to-Another-Repository@main   # @v1 or @main
        with:

          # required parameters
          target-filepath: 'README.md'     # file path to copy
          output-branch: 'master'  # branch name to create pull request
          output-repo: 'SatorImaging/OpenManual'
          git-token: ${{ secrets.Deploy2OM }}
